### PR TITLE
changes to Venue feature file

### PR DESCRIPTION
**Pull request by KishoreYarli**
@SuperstarDonkeyJockey @johnhud 
review and merge

### CODE REVIEW

**Comment by tadas-s** [comment]
@KishoreYarli I have absolutely no idea why I got a notification about this PR.

**Comment by harrygreen** [comment]
@tadas-s Me neither.
LGTM tho 👍

**Comment by tadas-s** [comment]
Yeah, looks good, I don't mind.

:+1:

**Comment by tadas-s** [comment]
Sooooo... What's up? Any news? How's everyone doing? :panda_face:

**Comment by SuperstarDonkeyJockey** [comment]
Haha! We're all good thanks :+1:

**Comment by KishoreYarli** [comment]
LoL!!! still reviewing our PR?
All good guys, how'z your new work happening..

**Pull request merged**
